# Array basics
Exercise 2A NumPy fundamentals
    

In [1]:
import numpy as np

In [2]:
fruits = ['apple' , 'banana' , 'cherry', 'date']
fruits

['apple', 'banana', 'cherry', 'date']

In [3]:
arr_1 = np.array(fruits)
# print(f"{arr_1}")
print(arr_1)
arr_1

['apple' 'banana' 'cherry' 'date']


array(['apple', 'banana', 'cherry', 'date'], dtype='<U6')

In [4]:
array_type = arr_1.dtype
array_type 

dtype('<U6')

The 'U' stands for Unicode string and the number '6' refers to either bytes per item or number of
Unicode characters stored 

In [5]:
arr_2 = np.array(((10,11,12),(13,14,15)))
arr_2

array([[10, 11, 12],
       [13, 14, 15]])

In [6]:
arr_2_T = arr_2.transpose() # or the following can be used :  arr_2_T = arr_2.T
arr_2_T

array([[10, 13],
       [11, 14],
       [12, 15]])

Transposing the data does not alter the value found in the data. It just switches the rows and columns of a dataset (Transposing is useful when you need to reorient your data for analysis or visualization)

In [7]:
arr_3 = np.array(((1,3,5),(2,4,6)))
arr_3

array([[1, 3, 5],
       [2, 4, 6]])

In [13]:
arr_4 = np.array(   ( (arr_3[0,2] , arr_3[1,1]) )   )
arr_4

array([5, 4])

In [18]:
arr_5 = np.array(   [ (1,1), (1,1), (1,1) ]   )
arr_5

array([[1, 1],
       [1, 1],
       [1, 1]])