In [68]:
import numpy as np

### Looping Through Arrays

In [69]:
arrA = np.array(   [[11,12],[13,14],[15,16]]  )
arrA.ndim
arrA

array([[11, 12],
       [13, 14],
       [15, 16]])

In [70]:
arrA.ndim

2

In [71]:
arrA.T

array([[11, 13, 15],
       [12, 14, 16]])

In [72]:
for x in arrA:
    print(x)
    

[11 12]
[13 14]
[15 16]


In [73]:
for x in arrA:
    for y in x:
        print(y)

11
12
13
14
15
16


First level loop runs against outermost dimension. Second level loop runs against inner most dimension. Each nested loop
runs against next inner dimension. The different results displays the different dimensions.

In [74]:
for x in arrA:
    loop_result2=(x*2)
    for y in x:
        loop_result = (y*2)
        print(y)
        print('')
        print(loop_result)
        print('')
        print(loop_result2)

#print(loop_result)
#loop_result2

11

22

[22 24]
12

24

[22 24]
13

26

[26 28]
14

28

[26 28]
15

30

[30 32]
16

32

[30 32]


### Joining and Stacking Arrays

In [75]:
joined_array_1 = np.concatenate((arrA,arrA), axis=0)
joined_array_1

array([[11, 12],
       [13, 14],
       [15, 16],
       [11, 12],
       [13, 14],
       [15, 16]])

In [76]:
joined_array_2 = np.concatenate((arrA,arrA), axis=1)
joined_array_2

array([[11, 12, 11, 12],
       [13, 14, 13, 14],
       [15, 16, 15, 16]])

In [77]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
stacked_array_1

array([[[11, 12],
        [13, 14],
        [15, 16],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [78]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))
stacked_array_2 
# Error message received: [ ValueError: all input arrays must have the same shape  ] Arrays with Different shapes cannot be stacked

ValueError: all input arrays must have the same shape

In [79]:
another_joined_array = np.concatenate((joined_array_1, arrA))
another_joined_array

array([[11, 12],
       [13, 14],
       [15, 16],
       [11, 12],
       [13, 14],
       [15, 16],
       [11, 12],
       [13, 14],
       [15, 16]])

In [80]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1)
another_2
# The size of the arrays have to be the same in order to concatenate. The array indexes have to have the same sized elements to join.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 6 and the array at index 1 has size 3

In [81]:
varhs = np.hstack((arrA,arrA))
print(varhs)
# This function stacks together arrays along the horizontal / rows axis 
print('')
varvs = np.vstack((arrA,arrA))
print(varvs)
# This function stacks arrays together along the vertical / columns axis
print('')
vards = np.dstack((arrA,arrA))
print(vards)
# This function stacks arrays together along the height / depth axis

[[11 12 11 12]
 [13 14 13 14]
 [15 16 15 16]]

[[11 12]
 [13 14]
 [15 16]
 [11 12]
 [13 14]
 [15 16]]

[[[11 11]
  [12 12]]

 [[13 13]
  [14 14]]

 [[15 15]
  [16 16]]]


### Splitting Arrays

In [82]:
splitsky = np.array_split(joined_array_1,2)
print(splitsky)
# The original array has been split into 2 different arrays, each with 1 dimension only, containing 3 pairs of elements within each dimension

[array([[11, 12],
       [13, 14],
       [15, 16]]), array([[11, 12],
       [13, 14],
       [15, 16]])]


In [83]:
splitterino = np.array_split(joined_array_1,3)
print(splitterino)
# The original array has been split into 3 different arrays, each array containig a single dimension and a pair of paired elements within each dimension

[array([[11, 12],
       [13, 14]]), array([[15, 16],
       [11, 12]]), array([[13, 14],
       [15, 16]])]


### Searching and Replacing Array Values.

In [84]:
result_1 = np.where(arrA % 2 == 0 , arrA, 'odd')
print('')
print(result_1)


[['odd' '12']
 ['odd' '14']
 ['odd' '16']]


### Sorting and Filtering Arrays

In [85]:
arrB = np.array( ((7,6),(13,5) , (7,3)) )
arrB


array([[ 7,  6],
       [13,  5],
       [ 7,  3]])

In [86]:
arrB.ndim

2

In [103]:
arrB_sorted = (np.sort(arrB))
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [104]:
print(arrB)
print('')
z = arrB < 7
arrC = arrB[z]
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]

[6 5 3]


In [105]:
print(arrB)
print('')
y = arrB > 7
arrD = arrB[y]
print(arrD)

[[ 7  6]
 [13  5]
 [ 7  3]]

[13]
